desc "Compile into report"
task :compile do
  `pdflatex final_paper.tex; open final_paper.pdf`
end

desc "Tar and gzip project"
task :tar do
  `tar czvf winterReport.tar.gz final_paper.tex final_paper.pdf`
end
