desc "Compile into report"
task :compile do
  `pandoc final_paper.tex -o team23WinterProgress.pdf ; open team23WinterProgress.pdf`
end

desc "Tar and gzip project"
task :tar do
  `tar czvf winterReport.tar.gz final_paper.tex team23WinterProgress.pdf`
end
